# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install requirements
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install -r requirements.txt
      - name: Run Prefect flow and check db is created
        run: |
          source .venv/bin/activate
          python3 flaskapp/transform.py
          ls flaskapp/compound_assay.sqlite
          [ -f flaskapp/compound_assay.sqlite ]
      - name: Run servers & curl both, checking for outputs from the api
        run: |
          source .venv/bin/activate
          python3 runservers.py &
          sleep 10
          curl -v --silent http://0.0.0.0:5000/api/compounds 2>&1 | grep C29H30F2N2O4
          curl -v --silent http://0.0.0.0:5000/api/assays 2>&1 | grep "Bromodomain-containing protein 2"
          curl -v --silent http://0.0.0.0:5000/api/compound/2193125 2>&1 | grep CCOC1=CC(=O)N(C)C=C1c2cc(NC(=O)Cc3cc(F)ccc3Cl)ccc2Oc4ccc(F)cc4F
          curl -v --silent http://0.0.0.0:5000/api/assay/18201147 2>&1 | grep 300000
          curl -v --silent http://0.0.0.0:8050/compounds 2>&1 | grep waitress
          curl -v --silent http://0.0.0.0:8050/assays 2>&1 | grep waitress
